version: '3.8'
services:
  userserviceapi:
    image: michaelbahchevanov1225/sweepi-users-service:latest
    build: src/UserService/UserServiceAPI
    ports:
      - '5100:5100'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  imageserviceapi:
    image: michaelbahchevanov1225/sweepi-images-service:latest
    build: src/ImageService
    ports:
      - '6969:6969'

  productserviceapi:
    image: michaelbahchevanov1225/sweepi-products-service
    build: src/ProductService/ProductServiceAPI
    ports:
      - '5300:5300'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  authenticationserviceapi:
    image: michaelbahchevanov1225/sweepi-auth-service:latest
    build: src/AuthenticationService/AuthenticationServiceAPI
    ports:
      - '42069:42069'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
