name: .NET Core UserService

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        working-directory: ./src/UserService/UserServiceAPI
        run: dotnet restore
      - name: Build
        working-directory: ./src/UserService/UserServiceAPI
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ./src/UserService/UserServiceAPI.IntegrationTests
        run: dotnet test --no-restore --verbosity normal

  path-context:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src/UserService/UserServiceAPI
          file: ./src/UserService/UserServiceAPI/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: michaelbahchevanov1225/sweepi-users-service:latest
