name: Node ImageService

on:
  push:
    branches: [master]
    paths:
      - 'src/ImageService'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test

  docker-build:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Tag Image
        run: |
          docker tag michaelbahchevanov1225/sweepi-images-service:latest
      - name: Docker Push
        run: |
          docker push michaelbahchevanov1225/sweepi-images-service:latest
